apiVersion: v1
kind: Service
metadata:
  name: mysql-master
  namespace: asiayo
spec:
  selector:
    app: mysql
    role: master
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None  # Headless Service，允許 StatefulSet 使用 DNS
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-slave
  namespace: asiayo
spec:
  selector:
    app: mysql
    role: slave
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None  # Headless Service，允許 StatefulSet 使用 DNS
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-router
  namespace: asiayo
spec:
  selector:
    app: mysql-router
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: LoadBalancer  # EKS 會分配一個外部 LoadBalancer
